// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://oqyonuvvgonehhronkxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xeW9udXZ2Z29uZWhocm9ua3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDIzNTUsImV4cCI6MjA2OTkxODM1NX0.Abaxzx7OCBoqTp0p32B7mx83j1cCoDJfd9IBCgmx7dY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
